### ISSUE TITLE
identity.email 权限无法检测

### ISSUE THREAD

**Issue by kiwiflydream** [Leizhenpeng/check-chrome-perms#1]
当前申请的权限如下：

"identity",
"identity.email"

涉及到的代码如下：

```js
chrome.identity.getProfileUserInfo({ accountStatus: "ANY" }, (info) => {
          this.loginEmail = info.email;
         //  使用 email 进行登录 
        });
```

检测时会提示 identity.email 权限没有用到，但是其实如果不声明 identity.email 。上面代码中获得的 info 是空对象，获得的 info.email 也是空字符串。

同理从 info 取 id 也需要对应的权限申请，不是只匹配到 identity 就可以，这点 chrome 设计的有点坑人。详细文档如下：https://developer.chrome.com/docs/extensions/reference/api/identity#type-ProfileUserInfo

**Comment by Leizhenpeng** [comment]
这绝对边缘case了哈哈,可以写个if ,欢迎pr!!
